### ISSUE TITLE
Organisation entries

### ISSUE THREAD

**Issue by Stormthirst** [ranguard/text-vcard#40]
I'm having some trouble with the module which I'm hoping you can help me with. 

When I run the code below:

use vCard::AddressBook;
my $address_book = vCard::AddressBook->new();
$address_book->load_file('Fake.Card.vcf');
print $address_book->as_string();
print "\n";

I get this:
BEGIN:VCARD
VERSION:3.0
N:Card;Card;;;
FN:Fake Card
EMAIL;TYPE=internet:fake.card@nowhere.com
END:VCARD

The vCard is attached, but here's the contents.
BEGIN:VCARD
VERSION:3.0
FN:Fake Card
N:Card;Card;;;
EMAIL;TYPE=WORK:fake.card@nowhere.com
ORG:Fake Card Org
END:VCARD

As you can see from the card there should be an entry for the Organisation, but the output from the script doesn't show an organisation. I've also been trying to use the same module to write vCards, but I can't see how to write the organisation either.

Am I missing something, or is this a bug?

Many thanks in advance,

Andrew

**Comment by ojwb** [comment]
It looks like PR #36 adds support for this.

**Comment by ranguard** [comment]
Fixed in #45 I believe - will release to CPAN soon

**Comment by worthmine** [comment]
I didn't add POD document. should I do? Or someone will do?

**Comment by ranguard** [comment]
Hi,

Yes, please could you add pod

Thanks

Leo
